// <auto-generated />
namespace localXchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedlanguagemodelssubscriptionmodelsandupdatedprofiletoreflectupdatedsettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedlanguagemodelssubscriptionmodelsandupdatedprofiletoreflectupdatedsettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201902090937491_added language models, subscription models and updated profile to reflect updated settings."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
